---
abstract: 'work with Mac plists at a low level'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mac-PropertyList
no_index:
  directory:
    - t
    - inc
requires:
  MIME::Base64: 0
  Math::BigInt: 0
  Scalar::Util: 1.11
  Time::Local: 0
  XML::Entities: 0
  parent: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Mac-PropertyList
  repository: git://github.com/briandfoy/mac-propertylist.git
version: 1.41
