# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mac-PropertyList
version:      0.9
version_from: lib/PropertyList.pm
installdirs:  site
requires:
    MIME::Base64:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
